# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(brulee)
    library(parsnip)
    library(recipes)
    library(workflows)
}
pin_loc <- pins:::github_raw("FarmerKE/mlops_lesson/master/pins-r/_pins.yaml")
b <- board_url(pin_loc)
v <- vetiver_pin_read(b, "penguins_model")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
