# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(brulee)
    library(parsnip)
    library(recipes)
    library(workflows)
}
b <- board_url(list(penguins_model = "https://raw.githubusercontent.com/FarmerKE/mlops_lesson/master/pins-r/penguins_model/20240218T191540Z-9cdcc/"))
v <- vetiver_pin_read(b, "penguins_model", version = "20240218T191540Z-9cdcc")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
